### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by myisaak** [myisaak/style-transfer#2]
Include screenshots and CI badge.

**Comment by MyIsaak** [comment]
Screenshot examples

![image](https://user-images.githubusercontent.com/4984415/69839784-4fe4b780-1259-11ea-9ff8-f2730a5727cc.png)
![image](https://user-images.githubusercontent.com/4984415/69839799-5c691000-1259-11ea-8700-805ab3604d66.png)
![image](https://user-images.githubusercontent.com/4984415/69839815-67bc3b80-1259-11ea-9659-6a60294ad459.png)

![image](https://user-images.githubusercontent.com/4984415/69839805-612dc400-1259-11ea-8779-ae5bbed78cc6.png)
